### PR TITLE
trying to get it to work with latest nengo commit, not successful!

### PR DESCRIPTION
**Pull request by adityagilra**
Hi, this is more of a request than a pull request. some new nengo commits have broken nengo_mpi. I tried to fix a few things, but some final stuff remains, which I can't figure out. Can you? Thanks.
tried to modify this to work with the latest nengo ver2 upto 12 May 2016: https://github.com/nengo/nengo/commit/8c97e218edfff42d5da95eb05ad9d32ae559509c

this seems to work with the git commit commit 5eab2ff4994fc5fc157f8dd0693f29c5ec9c8e7a , but not the above latest one.
After various simple edits I'm stuck with one regarding nengo.synapses.Lowpass as a nengo process.

### CODE REVIEW

**Comment by e2crawfo** [comment]
Can you try with the branch 'no_ublas'? Its a work-in-progress to get nengo_mpi up to date with nengo 2.1, I believe that its fairly close.

**Comment by adityagilra** [comment]
Hi Eric,

Thanks! The no_ublas branch works great!

I just had one issue with it:

In simulator.py line 185, I had to modify it to check if data is not empty:
                if len(data)>0:
					if data[0].shape != true_shape:
						data = map(
							partial(np.reshape, newshape=true_shape), data)

I was calling sim.run() multiple times in my code and on some calls, data would be empty.

I tried reproducing this in a separate small test script, but couldn't. I thought this might be if the 'sample_every' param for a probe is larger than the 'duration' in the sim.run(duration), then data might be zero length. But this worked fine in the test script. So am unsure why this happens in my script.

Anyway, this minor change corrects it. I just want to confirm with you that this fix is ok, and if you might know the reason? And if you'd want to put in the extra line for checking len(data)>0 into the codebase.

Thanks again,
Aditya.

**Comment by adityagilra** [comment]
Another issue. I was running the above without using mpirun i.e. just `python <scriptname>` (this actually turned out to be slower than the python reference).

Using mpirun (even with np 1), I get an error:
```
    sim = nengo_mpi.Simulator(mainModel,dt,partitioner=partitioner)
  File "/root/nengo_mpi/nengo_mpi/simulator.py", line 82, in __init__
    p = partitioner.partition(network)
  File "/root/nengo_mpi/nengo_mpi/partition/base.py", line 195, in partition
    network, can_cross_boundary)
  File "/root/nengo_mpi/nengo_mpi/partition/base.py", line 396, in network_to_cluster_graph
    post_cluster = cluster_map[post_obj]
KeyError: <LearningRule at 0x7f5dbe229050 modifying <Connection at 0x7f5dbe28c650 from <Neurons of <Ensemble (unlabeled) at 0x7f5dbe28c510>> to <Neurons of <Ensemble (unlabeled) at 0x7f5dbe28c510>>> with type PES(learning_rate=0.02, pre_tau=0.020000)>
```

**Comment by e2crawfo** [comment]
Sure, can you post the script that you are using?

**Comment by e2crawfo** [comment]
I'm going to close this for now and open new issues for each of the problems you found. For the empty Simulator.data problem, your solution definitely works but I'd like to find the underlying cause.

**Pull request closed without merging**
